# see https://github.com/rails/solid_cache?tab=readme-ov-file#cache-configuration for all options
# entries could be encrypted: https://github.com/rails/solid_cache?tab=readme-ov-file#enabling-encryption

default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default
  database: cache

test:
  <<: *default
  database: cache

production:
  <<: *default
  database: cache
