# NOTE
# The app uses currently 4 databases:
#   * the primary PostgreSQL database for ActiveRecord
#   * the cache SQLite database for SolidCache
#   * the cable SQLite database for SolidCable
#   * the queue SQLite database for SolidQueue

default: &default
  pool: <%= AppConf.rails_max_threads.to_i + 3 * AppConf.job_concurrency.to_i + 5 %>
  timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>

postgres: &postgres
  <<: *default
  adapter: postgresql
  connect_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  database: <%= AppConf.yournaling_db_name %>
  encoding: unicode
  host: <%= AppConf.yournaling_db_host %>
  migrations_paths: db/migrate
  password: <%= AppConf.yournaling_db_password %>
  port: <%= AppConf.yournaling_db_port.to_i %>
  read_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  reconnect: true
  username: <%= AppConf.yournaling_db_username %>
  variables:
    statement_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>

sqlite3: &sqlite3
  <<: *default
  adapter: sqlite3
  encoding: utf-8

cable_config: &cable_config
  <<: *sqlite3
  database: <%= "storage/#{AppConf.yournaling_db_name}_cable.sqlite3" %>
  migrations_paths: db/migrate_cable

cache_config: &cache_config
  <<: *sqlite3
  database: <%= "storage/#{AppConf.yournaling_db_name}_cache.sqlite3" %>
  migrations_paths: db/migrate_cache

queue_config: &queue_config
  <<: *sqlite3
  database: <%= "storage/#{AppConf.yournaling_db_name}_queue.sqlite3" %>
  migrations_paths: db/migrate_queue

development:
  primary:
    <<: *postgres
  cable:
    <<: *cable_config
  cache:
    <<: *cache_config
  queue:
    <<: *queue_config

test:
  # unfortunately yournaling_db_name_test is necessary, as some `rake db:` commands work against dev & test env
  primary:
    <<: *postgres
    database: <%= AppConf.yournaling_db_name_test %>
  cable:
    <<: *cable_config
    database: <%= "storage/#{AppConf.yournaling_db_name_test}_cable.sqlite3" %>
  cache:
    <<: *cache_config
    database: <%= "storage/#{AppConf.yournaling_db_name_test}_cache.sqlite3" %>
  queue:
    <<: *queue_config
    database: <%= "storage/#{AppConf.yournaling_db_name_test}_queue.sqlite3" %>

production:
  primary:
    <<: *postgres
  cable:
    <<: *cable_config
  cache:
    <<: *cache_config
  queue:
    <<: *queue_config
