default: &default
  adapter: postgresql
  connect_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  database: <%= AppConf.yournaling_db_name %>
  encoding: unicode
  host: <%= AppConf.yournaling_db_host %>
  password: <%= AppConf.yournaling_db_password %>
  # pool: <%= AppConf.rails_max_threads.to_i * AppConf.web_concurrency.to_i + 10 %>
  pool: <%= AppConf.rails_max_threads.to_i + 3 + AppConf.good_job_max_threads.to_i + 2 %>
  port: <%= AppConf.yournaling_db_port.to_i %>
  read_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  reconnect: true
  timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  username: <%= AppConf.yournaling_db_username %>
  variables:
    statement_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>

development:
  <<: *default

test:
  <<: *default
  # unfortunately necessary, as some `rake db:` commands work against dev & test env
  database: <%= AppConf.yournaling_db_name_test %>

production:
  <<: *default
