default: &default
  adapter: postgresql
  connect_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  database: <%= AppConf.yournaling_db_name %>
  encoding: unicode
  host: <%= AppConf.yournaling_db_host %>
  password: <%= AppConf.yournaling_db_password %>
  pool: <%= AppConf.rails_max_threads.to_i + 3 * AppConf.job_concurrency.to_i + 5 %>
  port: <%= AppConf.yournaling_db_port.to_i %>
  read_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  reconnect: true
  timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>
  username: <%= AppConf.yournaling_db_username %>
  variables:
    statement_timeout: <%= AppConf.yournaling_db_timeout_seconds.to_i * 1000 %>

development:
  primary: &primary_development
    <<: *default
  cable:
    <<: *primary_development
    database: <%= "#{AppConf.yournaling_db_name}_cable" %>
    migrations_paths: db/migrate_cable
  cache:
    <<: *primary_development
    database: <%= "#{AppConf.yournaling_db_name}_cache" %>
    migrations_paths: db/migrate_cache
  queue:
    <<: *primary_development
    database: <%= "#{AppConf.yournaling_db_name}_queue" %>
    migrations_paths: db/migrate_queue

test:
  primary: &primary_test
    <<: *default
    # unfortunately necessary, as some `rake db:` commands work against dev & test env
    database: <%= AppConf.yournaling_db_name_test %>
  cable:
    <<: *primary_test
    database: <%= "#{AppConf.yournaling_db_name_test}_cable" %>
    migrations_paths: db/migrate_cable
  cache:
    <<: *primary_test
    database: <%= "#{AppConf.yournaling_db_name_test}_cache" %>
    migrations_paths: db/migrate_cache
  queue:
    <<: *primary_test
    database: <%= "#{AppConf.yournaling_db_name_test}_queue" %>
    migrations_paths: db/migrate_queue

production:
  primary: &primary_production
    <<: *default
  cable:
    <<: *primary_production
    database: <%= "#{AppConf.yournaling_db_name}_cable" %>
    migrations_paths: db/migrate_cable
  cache:
    <<: *primary_production
    database: <%= "#{AppConf.yournaling_db_name}_cache" %>
    migrations_paths: db/migrate_cache
  queue:
    <<: *primary_production
    database: <%= "#{AppConf.yournaling_db_name}_queue" %>
    migrations_paths: db/migrate_queue
